#!/bin/bash

# This script was tested in the following env:
# - Intel(R) Core(TM) i5-7260U CPU
# - Ubuntu 20.04 LTS
# - needs adjustment depending on OS/CPU model
#   https://www.kernel.org/doc/Documentation/cpu-freq/intel-pstate.txt

# Is acpi-cpufreq being used?
drv=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver`
if [ ! $drv == "acpi-cpufreq" ]; then
 echo "`tput bold``tput setaf 1`";
 echo "ERROR: edit /etc/default/grub to disable intel_pstate:";
 echo "  GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash intel_pstate=disable\"";
 echo "sudo update-grub";
 echo "reboot";
 echo "`tput sgr0`";
 exit
fi

# Turn off hyperthreading
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | \
cut -d',' -f2 | sort -u | \
while read cpuid; do \
 echo "Disabling CPU $cpuid"; \
 echo 0 > /sys/devices/system/cpu/cpu$cpuid/online; \
done 

# Turn off boost
echo "Disabling boost"; \
echo 0 > /sys/devices/system/cpu/cpufreq/boost

# Set frequency
# TODO: check if usermode is in available list of governors
# - cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors 
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | \
cut -d',' -f1 | sort -u | \
while read cpuid; do \
  saf=`cut -d' ' -f2 /sys/devices/system/cpu/cpu$cpuid/cpufreq/scaling_available_frequencies`; \
  echo "Setting frequency to $saf in CPU $cpuid"; \
  echo userspace > /sys/devices/system/cpu/cpu$cpuid/cpufreq/scaling_governor; \
  echo $saf > /sys/devices/system/cpu/cpu$cpuid/cpufreq/scaling_setspeed; \
done

