#!/bin/bash

# This script was tested in the following env:
# - Intel(R) Core(TM) i5-7260U CPU
# - Ubuntu 20.04 LTS
# - needs adjustment depending on OS/CPU model
#   https://www.kernel.org/doc/Documentation/cpu-freq/intel-pstate.txt

# Is acpi-cpufreq being used?
drv=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver`
if [ ! $drv == "intel_pstate" ]; then
 echo "`tput bold``tput setaf 1`";
 echo "ERROR: edit /etc/default/grub to NOT disable intel_pstate:";
 echo "  GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"";
 echo "sudo update-grub";
 echo "reboot";
 echo "`tput sgr0`";
 exit
fi

# Turn off hyperthreading
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | \
cut -d',' -f2 | sort -u | \
while read cpuid; do \
 echo "Disabling CPU $cpuid"; \
 echo 0 > /sys/devices/system/cpu/cpu$cpuid/online; \
done 

# Turn off turbo-boost
echo "Disabling Turbo Boost"; \
echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo

