#!/bin/bash

version=20200906
where="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
top=$where/../

cd $top
wget https://bench.cr.yp.to/supercop/supercop-$version.tar.xz
unxz < supercop-$version.tar.xz | tar -xf -
